# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('dis', models.TextField()),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=900)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
