# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='dis',
            new_name='description',
        ),
    ]
