# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_list', '0002_auto_20170518_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='category',
            field=models.CharField(choices=[('Auto', 'Autolist'), ('Edu', 'Edulist')], default='Auto', max_length=2),
        ),
    ]
