# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_list', '0003_about_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='about',
            name='category',
            field=models.CharField(choices=[('Automotive', 'Automotive'), ('Education_Learning', 'Education & Learning'), ('Entertainment', 'Entertainment'), ('Financial_Services', 'Financial Services'), ('Hair_Beauty', 'Hair Beauty'), ('Medical', 'Medical'), ('Professional_Services', 'Professional Services'), ('Restaurants', 'Restaurants'), ('Retail_Shopping', 'Retail Shopping'), ('Sports_Recreation', 'Sports Recreation'), ('Trades', 'Trades'), ('Other', 'Other')], default='Automotive', max_length=100),
        ),
    ]
