# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_list', '0004_auto_20170521_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/mnt/project/media/images/barcelona.jpg', upload_to='images'),
        ),
    ]
