# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz_list', '0005_auto_20170612_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='profile_pic',
        ),
    ]
