# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_list', '0008_auto_20170616_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='brief_description',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
