# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_list', '0009_auto_20170616_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='pin',
            new_name='pinterest',
        ),
        migrations.AlterField(
            model_name='about',
            name='brief_description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
