# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_list', '0012_auto_20170621_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='category',
            field=models.CharField(choices=[('Automotive', 'Automotive'), ('Education_Learning', 'Education & Learning'), ('Entertainment', 'Entertainment'), ('Financial_Services', 'Financial Services'), ('Hair_Beauty', 'Hair Beauty'), ('Medical', 'Medical'), ('Services', 'Services'), ('Restaurants', 'Restaurants'), ('Retail_Shopping', 'Retail Shopping'), ('Sports_Recreation', 'Sports Recreation'), ('Real_Estate', 'Real Estate'), ('Other', 'Others')], default='Automotive', max_length=100),
        ),
    ]
