# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_list', '0013_auto_20170621_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
