# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_list', '0014_about_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='published',
        ),
        migrations.AddField(
            model_name='about',
            name='approved_published',
            field=models.BooleanField(default=False),
        ),
    ]
